[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  included_files = [
    "node_modules/ffmpeg-static/ffmpeg",
    "node_modules/ffmpeg-static/ffmpeg.exe",
    "assets/fonts/*.ttf",
  ]
  external_node_modules = ["ffmpeg-static"]

[functions."*"]
  timeout = 100